.PHONY: unit-tests test-factory-install test-factory-configure

WS=ignored/testing/$(ENV_NUMBER)
FACTORY_VENV=${WS}/factory

## @Testing runs unit tests
unit-tests: ## runs unit tests for the project
	mkdir -p reports/junit/
	poetry run nose2 --pretty-assert -F --verbose --coverage-report html --coverage-report term --coverage-report xml -C

## @Testing installs factory into given ENV_NUMBER
test-factory-install:
	poetry install

## @Testing configures current profile by uploading config and bootstrapping a branch for the given ENV_NUMBER
test-factory-configure:
	poetry run servicecatalog-factory upload-config servicecatalog_factory/example-config-small.yaml
	poetry run servicecatalog-factory bootstrap-branch "$$(git rev-parse --abbrev-ref HEAD)"

## @Testing runs generate-via-luigi for current profile in the given ENV_NUMBER
test-factory-generate-via-luigi:
	poetry run servicecatalog-factory --info ignored/src/ServiceCatalogFactory/portfolios/

unit-test-watcher: ## runs unit tests for the project
	find servicecatalog_factory -name '*.py' | entr poetry run nose2 --pretty-assert --verbose
