# Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: |
  Lambda for backing custom resources to create an AWS Account

Parameters:
  AssumableOrgRoleArn:
    Type: AWS::SSM::Parameter::Value<String>
    Description: IAM role to assume that enables Organizations access to create and move the cereated account
    Default: AssumableOrgRole

Resources:
  AccountCustomResourceRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /account-vending/
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: ServiceCatalogActions
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - sts:AssumeRole
                Resource: !Ref AssumableOrgRoleArn
              - Effect: Allow
                Action:
                  - ssm:GetParameter
                Resource: !Ref AssumableOrgRoleArn
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action:
              - "sts:AssumeRole"
          - Effect: "Allow"
            Principal:
              Service:
                - "lambda.amazonaws.com"
            Action:
              - "sts:AssumeRole"

  AccountCustomResource:
    Type: AWS::Serverless::Function
    Description: |
      The lambda function that creates an account when called using a CloudFormation Custom Resource:
      ```yaml
      Account:
        Type: Custom::CustomResource
        Description: A custom resource representing an AWS Account
        Properties:
          ServiceToken: !Ref AccountVendingCreationLambda
          Email: !Ref Email
          AccountName: !Ref AccountName
          OrganizationAccountAccessRole: !Ref OrganizationAccountAccessRole
          IamUserAccessToBilling: !Ref IamUserAccessToBilling
          TargetOU: !Ref TargetOU
      ```
    Properties:
      CodeUri: ./src
      Handler: handler.handler
      Description: Lambda for accepting shares
      Role: !GetAtt AccountCustomResourceRole.Arn
      Runtime: python3.7
      Timeout: 30
      Environment:
        Variables:
          ASSUMABLE_ORG_ROLE_ARN: !Ref AssumableOrgRoleArn

  Param:
    Type: AWS::SSM::Parameter
    Description: |
      Outputs the AccountCustomResource Arn to an SSM param named ```account-vending-creation-lambda```
    Properties:
      Name: account-vending-creation-lambda
      Type: String
      Value: !GetAtt AccountCustomResource.Arn


Outputs:
  AccountId:
    Value: !GetAtt AccountCustomResource.Arn
