# Copyright 2021 Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

AWSTemplateFormatVersion: "2010-09-09"

Conditions:
  ShouldDoAnything: !Equals [ true, false]

Resources:
  NoOp:
    Type: AWS::S3::Bucket
    Condition: ShouldDoAnything