#  Copyright 2022 Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: Apache-2.0


CACHE_INVALIDATOR = "SCT_CACHE_INVALIDATOR"

AWS_URL_SUFFIX = "AWS_URL_SUFFIX"

CODE_BUILD_PROJECT_ENVIRONMENT_IMAGE = "SCF_CODE_BUILD_PROJECT_ENVIRONMENT_IMAGE"
