# Copyright 2021 Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
schema;seq_tags:
  type: map
  mapping:
    Key:
      type: str
    Value:
      type: str

schema;map_component:
  type: map
  mapping:
    Name:
      type: str
    Owner:
      type: str
    Description:
      type: str
    Distributor:
      type: str
    SupportDescription:
      type: str
    SupportEmail:
      type: str
      pattern: .+@.+
    SupportUrl:
      type: str
      pattern: https?://(?:[-\w.]|(?:%[\da-fA-F]{2}))+
    BuildSpecImage:
      type: str
    BuildSpec:
      type: str
    Source:
      type: map
      mapping:
        Provider:
          type: str
        Configuration:
          type: map
          mapping:
            RepositoryName:
              type: str
            BranchName:
              type: str
            Branch:
              type: str
            Owner:
              type: str
            Repo:
              type: str

    Options:
      type: map
      mapping:
        ShouldCFNNag:
          type: bool
        ShouldCloudformationRSpec:
          type: bool
    Tags:
      type: seq
      sequence:
        - include: seq_tags
    Versions:
      type: seq
      sequence:
        - type: map
          mapping:
            Name:
              type: str
            Description:
              type: str
            Tags:
              type: seq
              sequence:
                - include: seq_tags
            Active:
              type: bool
            Options:
              type: map
              mapping:
                ShouldCFNNag:
                  type: bool
                ShouldCloudformationRSpec:
                  type: bool
            BuildSpecImage:
              type: str
            BuildSpec:
              type: str
            Source:
              type: map
              mapping:
                Provider:
                  type: str
                Configuration:
                  type: map
                  mapping:
                    RepositoryName:
                      type: str
                    BranchName:
                      type: str
                    Branch:
                      type: str
                    Owner:
                      type: str
                    Repo:
                      type: str
type: map
mapping:
  Schema:
    type: str
    enum: ['factory-2019-04-01']
    required: yes
  Portfolios:
    type: seq
    sequence:
      - type: map
        mapping:
          DisplayName:
            type: str
            required: yes
          Description:
            type: str
            required: yes
          ProviderName:
            type: str
            required: yes
          Associations:
            type: seq
            sequence:
              - type: str
          Tags:
            type: seq
            sequence:
              - include: seq_tags
          Components:
            type: seq
            sequence:
              - include: map_component
