# Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

AWSTemplateFormatVersion: "2010-09-09"
Description: |
  Initialiser template used to bring up the install ServiceCatalog-Factory
  {"version": "0.25.0", "framework": "servicecatalog-factory", "role": "initialiser"}

Parameters:
  Version:
    Type: String
    Default: "0.25.0"
    Description: |
      Which version of aws-service-catalog-factory to install
  EnabledRegions:
    Type: String
    Description: |
      Space or comma seperated list of AWS Regions for which your Factory should operate in

Resources:
  Param:
    Type: AWS::SSM::Parameter
    Properties:
      Name: service-catalog-factory-initialiser-version
      Type: String
      Value: !Ref Version

  InitialiserRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: Initialiser
      Path: /servicecatalog-product-factory/
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "codebuild.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess

  InitialiserProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: servicecatalog-product-factory-initialiser
      Description: "Initialiser for the framework"
      ServiceRole: !GetAtt InitialiserRole.Arn
      Artifacts:
        Type: NO_ARTIFACTS
      Environment:
        Type: linuxContainer
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/python:3.7.1
        EnvironmentVariables:
          - Name: VERSION
            Type: PLAINTEXT
            Value: !Ref Version
          - Name: ENABLED_REGIONS
            Type: PLAINTEXT
            Value: !Ref EnabledRegions
      Source:
        Type: NO_SOURCE
        BuildSpec: !Sub |
          version: 0.2
          phases:
            install:
              commands:
                - pip install aws-service-catalog-factory=={{VERSION}}
                - servicecatalog-factory --info set-regions {{ENABLED_REGIONS}}
            build:
              commands:
                - servicecatalog-factory --info bootstrap

      TimeoutInMinutes: 60

Outputs:
  Version:
    Value: !GetAtt Param.Value