# Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

AWSTemplateFormatVersion: "2010-09-09"
Description: |
  Bootstrap template used to bring up a region for use with ServiceCatalog-Factory AWS CodePipeline
  {"version": "{{ VERSION }}", "framework": "servicecatalog-factory", "role": "bootstrap-region"}

Parameters:
  Version:
    Type: String
    Default: "{{ VERSION }}"

Resources:
  Param:
    Type: AWS::SSM::Parameter
    Properties:
      Name: service-catalog-factory-regional-version
      Type: String
      Value: !Ref Version

  PipelineArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "sc-factory-artifacts-${AWS::AccountId}-${AWS::Region}"
      VersioningConfiguration:
        Status: Enabled

Outputs:
  Version:
    Value: !GetAtt Param.Value