name: CodeCov
on: [push, pull_request]
jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7]
        poetry-version: [1.2.0]
        os: [ubuntu-18.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}
      # https://github.com/python-poetry/poetry/issues/4511
      - name: setuptools < 58.0.0
        run: poetry run pip install 'setuptools==57.5.0'
      - name: Install
        run: make install
      - name: run tests
        run: make unit-tests
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v1

